---
- name: Deploy ELK stack locally
  hosts: elk_server
  connection: local
  become: true

  roles:
    - role: docker
      tags: docker

    - role: elk
      tags: elk


- name: Configure OT monitoring endpoint
  hosts: ot_endpoints
  become: true

  roles:
    - role: openplc
      tags: openplc

    - role: zeek
      tags: zeek

    - role: filebeat
      tags: filebeat